# Generated by Django 6.0.5 on 2026-06-08 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsondocs', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondocument',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='json_documents', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='jsondocument',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
