# Generated by Django 6.0.5 on 2026-06-08 08:42

import json
from django.db import migrations

def create_default_workspaces(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Workspace = apps.get_model('workspaces', 'Workspace')
    
    TodoTask = apps.get_model('todos', 'TodoTask')
    TodoList = apps.get_model('todos', 'TodoList')
    Note = apps.get_model('notes', 'Note')
    TableSheet = apps.get_model('tables', 'TableSheet')
    JsonDocument = apps.get_model('jsondocs', 'JsonDocument')
    MarkdownDocument = apps.get_model('markdown', 'MarkdownDocument')
    CodeDocument = apps.get_model('codefiles', 'CodeDocument')
    
    # Using python built-in list since we can't import the constant easily
    default_tools = ['todos', 'notes', 'tables', 'jsondocs', 'markdown', 'codefiles']
    
    for user in User.objects.all():
        workspace, created = Workspace.objects.get_or_create(
            user=user,
            is_default=True,
            defaults={'name': 'Personal Workspace', 'enabled_tools': default_tools}
        )
        
        TodoTask.objects.filter(user=user, workspace__isnull=True).update(workspace=workspace)
        TodoList.objects.filter(user=user, workspace__isnull=True).update(workspace=workspace)
        Note.objects.filter(user=user, workspace__isnull=True).update(workspace=workspace)
        TableSheet.objects.filter(user=user, workspace__isnull=True).update(workspace=workspace)
        JsonDocument.objects.filter(user=user, workspace__isnull=True).update(workspace=workspace)
        MarkdownDocument.objects.filter(user=user, workspace__isnull=True).update(workspace=workspace)
        CodeDocument.objects.filter(user=user, workspace__isnull=True).update(workspace=workspace)

def reverse_default_workspaces(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        ('todos', '0002_todolist_workspace_todotask_workspace'),
        ('notes', '0003_note_workspace'),
        ('tables', '0002_tablesheet_workspace'),
        ('jsondocs', '0002_jsondocument_workspace_alter_jsondocument_content'),
        ('markdown', '0002_markdowndocument_workspace'),
        ('codefiles', '0002_codedocument_workspace'),
    ]

    operations = [
        migrations.RunPython(create_default_workspaces, reverse_default_workspaces),
    ]
